//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace N1990.Episerver.Cms.Audit {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.3.0.0")]
    internal sealed partial class web : global::System.Configuration.ApplicationSettingsBase {
        
        private static web defaultInstance = ((web)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new web())));
        
        public static web Default {
            get {
                return defaultInstance;
            }
        }
    }
}
